#!/usr/bin/env bash

set -eu
set -o pipefail

readonly PROG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly STACK_DIR="$(cd "${PROG_DIR}/.." && pwd)"
readonly BIN_DIR="${STACK_DIR}/.bin"
readonly BUILD_DIR="${STACK_DIR}/build"

echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
echo "PROG_DIR=$PROG_DIR"
echo "STACK_DIR=$STACK_DIR"
echo "BUILD_DIR=$BUILD_DIR"

# shellcheck source=SCRIPTDIR/.util/tools.sh
source "${PROG_DIR}/.util/tools.sh"

# shellcheck source=SCRIPTDIR/.util/print.sh
source "${PROG_DIR}/.util/print.sh"

function main() {
  local build run receiptFilename buildReceipt runReceipt receipts
  build="${BUILD_DIR}/build.oci"
  run="${BUILD_DIR}/run.oci"
  receiptFilename="receipt.cyclonedx.json"
  buildReceipt="${BUILD_DIR}/build-${receiptFilename}"
  runReceipt="${BUILD_DIR}/run-${receiptFilename}"

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --help|-h)
        shift 1
        usage
        exit 0
        ;;

      --build-image|-b)
        build="${2}"
        shift 2
        ;;

      --run-image|-r)
        run="${2}"
        shift 2
        ;;

      --build-receipt|-B)
        buildReceipt="${2}"
        shift 2
        ;;

      --run-receipt|-R)
        runReceipt="${2}"
        shift 2
        ;;

      "")
        # skip if the argument is empty
        shift 1
        ;;

      *)
        util::print::error "unknown argument \"${1}\""
    esac
  done

  tools::install

  # We are generating receipts for all platforms but copying the amd64 receipts as $buildReceipt and $runReceipt
  receipts::generate::multi::arch "${build}" "${run}"

  receipts=$(find $BUILD_DIR -type f -name "*${receiptFilename}" | sed 's/^/  /g')
  util::print::success "Success! Receipts are:\n${receipts}\n"
}

function usage() {
  cat <<-USAGE
receipts.sh [OPTIONS]

Generates receipts listing packages installed on build and run images of the
stack.

OPTIONS
  --help          -h  prints the command usage
  --build-image   -b  path to OCI image of build image. Defaults to
                      ${BUILD_DIR}/build.oci
  --run-image     -r  path to OCI image of build image
                      ${BUILD_DIR}/run.oci
  --build-receipt -B  path to output build image package receipt. Defaults to
                      ${BUILD_DIR}/build-receipt.txt
  --run-receipt   -R  path to output run image package receipt. Defaults to
                      ${BUILD_DIR}/run-receipt.txt
USAGE
}

function tools::install() {
  util::tools::syft::install \
    --directory "${BIN_DIR}"
  util::tools::crane::install \
    --directory "${BIN_DIR}"
}

function receipts::generate() {
  local image output

  image="${1}"
  output="${2}"

  util::print::title "Generating package SBOM for ${image}"

  util::print::info "Generating CycloneDX package SBOM using syft"
  syft packages "${image}" --output cyclonedx-json --file "${output}"
}

# Generates syft receipts for each architecture for given oci archives
function receipts::generate::multi::arch() {
  local buildArchive runArchive registryPort registryPid localRegistry imageType archiveName imageReceipt

  buildArchive="${1}"
  runArchive="${2}"

  # This is hard-coded, but a random port could be obtained if needed
  registryPort=54321

  # Start a local in-memory registry so we can work with the oci archives
  PORT=$registryPort crane registry serve --insecure > /dev/null 2>&1 &
  registryPid=$!

  sleep 2

  localRegistry="127.0.0.1:$registryPort"

  # Push the oci archives to the local registry
  jam publish-stack \
    --build-ref "$localRegistry/build" \
    --build-archive $buildArchive \
    --run-ref "$localRegistry/run" \
    --run-archive $runArchive
  
  # Ensure we can write to the BUILD_DIR
  if [ $(stat -c %u build) = "0" ]; then
    sudo chown -R "$(id -u):$(id -g)" "$BUILD_DIR"
  fi

  for imageType in build run; do
    archiveName="${imageType}.oci"
    util::print::title "Generating package SBOM for ${archiveName}"

    for imageArch in $(crane manifest "$localRegistry/$imageType" | jq -r '.manifests[].platform.architecture'); do
      util::print::info "Generating CycloneDX package SBOM using syft for $archiveName on platform linux/$imageArch"

      imageReceipt="${BUILD_DIR}/${imageType}-${imageArch}-${receiptFilename}"

      # Generate the architecture-specific SBOM from image in the local registry
      syft packages "registry:$localRegistry/$imageType" \
        --output cyclonedx-json \
        --file "$imageReceipt" \
        --platform "linux/$imageArch"

      # Copy the amd64 image receipt as the primary one generated by this script
      if [ $(util::tools::arch) = "amd64" ]; then
        cp "$imageReceipt" "${BUILD_DIR}/${imageType}-${receiptFilename}"
      fi
    done
  done

  kill $registryPid
}

main "${@:-}"
